### ISSUE TITLE
List HTML validation tools you know.

### ISSUE THREAD

**Issue by daoanhhuy26012001** [daoanhhuy26012001/Intern_Training#11]
- The Nu HTML Validator
- Aborla HTML Validator
- Total HTML Validator
- Markup Validation Service

**Comment by nvkhanh08t4** [comment]
Online tools:
https://validator.w3.org/
https://www.freeformatter.com/html-validator.html
https://appdevtools.com/html-validator

**Comment by daoanhhuy26012001** [comment]
tks !
